### PR TITLE
Bring the `1.x` branch up to date with `main`

### PR DESCRIPTION
**Pull request by Xtansia**
### Description
Brings the `1.x` branch up to date with `main`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by VachaShah** [comment]
Looks like some commits have DCO issues?

**Comment by Xtansia** [comment]
> Looks like some commits have DCO issues?

@VachaShah Yeah, there's a handful of commits where the squash merge has used a different author to what was used in the DCO. ie. DCO was with `@amazon.com` address, but squash merge has been attributed to their GitHub `@users.noreply.github.com` address.

Not much that can be done about that as they're in main.

**Comment by Yury-Fridlyand** [comment]
Is there something in `1.x` which is missing in `main`? If no, you can delete `1.x` and then re-create it.
If yes, but amount of changes (commits) is pretty small, you can recreate the branch and cherry-pick those changes.
To avoid a mistake you can rename `1.x` and delete once confirmed that everything is correct.

**Comment by Xtansia** [comment]
@Yury-Fridlyand Branch protection rules mean I do not have permission to delete or update the `1.x` branch. Yes, the branch is "fast-forwardable".

**Comment by Yury-Fridlyand** [comment]
Well, you can force-push to `1.x` from `main` if you're sure that nothing to lose.

**Comment by Xtansia** [comment]
@Yury-Fridlyand Again, the branch protection rules mean I am unable to (force-)push to `1.x`

**Comment by Yury-Fridlyand** [comment]
Oh no!
I just tried to find a way to avoid reviewing 400+ files in this PR...

**Comment by Xtansia** [comment]
@Yury-Fridlyand I'll try getting some temporary permissions to get things in order and save having to review this

**Pull request closed without merging**
