### PR TITLE
Bump the version.

### PR DESCRIPTION
**Pull request by Yury-Fridlyand**
Signed-off-by: Yury-Fridlyand <yuryf@bitquilltech.com>

### Description
Bump release version to `1.1.0`.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
We should be doing this every time _after_ a release, preparing for the next developer iteration.

**Comment by Yury-Fridlyand** [comment]
This goes to the `main`, not to `1.1.0` branch.

**Comment by harshavamsi** [comment]
> We should be doing this every time _after_ a release, preparing for the next developer iteration.

@dblock correct me if I'm wrong here, but shouldn't this be done _before_ a release. The release artifacts still point to the older `1.0.0` version unless we update them here first.

**Review by wbeckler — APPROVED** [review]

**Comment by dblock** [comment]
@harshavamsi My favorite reason why version should be incremented to the next development iteration right _after_ a release is because I don't ever want to rebuild code with changes that happened after the said release. So let's say we release 1.0.0, the next patch version is always 1.0.1 per semver (incremented immediately) and there's never again a 1.0.0 build.

**Pull request merged**
