### PR TITLE
Added dependabot_changelog workflow to update changelog for dependabot

### PR DESCRIPTION
**Pull request by nhtruong**
Signed-off-by: Theo Truong <theotr@amazon.com>

### CODE REVIEW

**Review by dblock — DISMISSED** [review]

**Comment by VachaShah** [comment]
@nhtruong Can you please sign off your commit and add a CHANGELOG entry?

**Comment by nhtruong** [comment]
@VachaShah DCO is still failing for some reason

**Comment by VachaShah** [comment]
```
Commit sha: [b3f00f1](https://github.com/opensearch-project/opensearch-net/pull/118/commits/b3f00f102ee94dd956f128d1fdc3c2e351b989f7), Author: Theo Nam Truong, Committer: GitHub; Expected "Theo Nam Truong [theotr@amazon.com](mailto:theotr@amazon.com)", but got "Theo Truong [theotr@amazon.com](mailto:theotr@amazon.com)".
```

**Comment by VachaShah** [comment]
Your signature name is different than your account

**Review by VachaShah — APPROVED** [review]

**Review by dblock — CHANGES_REQUESTED** [review]
For a client I think we should make dependabot add a CHANGELOG line instead. The version dependencies are kinda important because they have downstream impact. 
https://github.com/marketplace/actions/dependabot-changelog-helper

**Comment by nhtruong** [comment]
@VachaShah 
```
Commit sha: [b3f00f1](https://github.com/opensearch-project/opensearch-net/pull/118/commits/b3f00f102ee94dd956f128d1fdc3c2e351b989f7), Author: Theo Nam Truong, Committer: GitHub; Expected "Theo Nam Truong [theotr@amazon.com](mailto:theotr@amazon.com)", but got "Theo Truong [theotr@amazon.com](mailto:theotr@amazon.com)".
Commit sha: [8fdf305](https://github.com/opensearch-project/opensearch-net/pull/118/commits/8fdf3057a1e71399843184df3a76d5243e6a3928), Author: Theo Truong, Committer: Theo Truong; Expected "Theo Truong [theotr@amazon.com](mailto:theotr@amazon.com)", but got "Theo Nam Truong [theotr@amazon.com](mailto:theotr@amazon.com)".
```
Shall we solve this Github riddle? haha

**Comment by dblock** [comment]
This LGTM, can you please fix DCO?

**Review by dblock — APPROVED** [review]

**Review by VachaShah — APPROVED** [review]

**Pull request merged**
