### PR TITLE
Add higher-level HTTP DSL methods

### LINKED ISSUE #403: [FEATURE] Make raw JSON REST requests to OpenSearch
### Is your feature request related to a problem?

Coming from https://github.com/opensearch-project/opensearch-clients/issues/62, add support for making raw JSON requests.

### What solution would you like?

1. If an existing mechanism exists, document it similar to https://github.com/opensearch-project/opensearch-py/pull/542. 
2. Add a high level DSL, e.g. `client.get` and `client.post`.

### PR DESCRIPTION
**Pull request by Xtansia**
### Description
Adds the higher-level HTTP DSL methods to wrap `DoRequest` and allow better ergonomics.

### Issues Resolved
Closes #403 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — COMMENTED** [review]
Why do we need `.LowLevel` at all?

**Comment by Xtansia** [comment]
> Why do we need `.LowLevel` at all?

All requests are eventually handled via `.LowLevel`/`OpenSearch.Net`. However in future it'd be ideal to simplify and only have a single client package keeping just the transport layer separate, similar to what NEST did in v8.

**Review by dblock — APPROVED** [review]
Looks OK. I think I'd remove any mention of `LowLevel` from the documentation. In my opinion writing `client.Http.GetAsync` is 100x better.

**Comment by Xtansia** [comment]
Converting to draft as there's some naming conventions that need fixing or excluding from conventions tests

**Review by dblock — APPROVED** [review]
Retry tests till they pass? 😢

**Pull request merged**
