### PR TITLE
[Backport 1.x] Bump BenchMarkDotNet, xunit, xunit.runner.visualstudio & CSharpier.Core

### PR DESCRIPTION
**Pull request by Xtansia**
### Description
Backports recent dependabot PRs to 1.x

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dblock — APPROVED** [review]
Curious why we're still releasing a 1.x line of the client?

**Comment by Xtansia** [comment]
> Curious why we're still releasing a 1.x line of the client?

@dblock We only have a 1.x line released so far, there's not been a breaking 2.x release of the client yet

**Comment by dblock** [comment]
Any advantage of maintaining a 1.x vs. moving forward with a breaking 2.x?

**Comment by Xtansia** [comment]
@dblock Just hasn't been anything urgently breaking to cut it yet, but wanting to at least finish re-generating the core APIs to capture any potential breakages/renames/deprecations in that before cutting 2.x. Once the JSON serialization work and potential accompanying client refactoring gets done that'll be another major break too.

**Pull request merged**
